class Planet {
  static List planetList = [
    {
      'name': 'Earth',
      'file': 'assets/images/Earth.glb',
      'year' : '365 Earth Day',
      'type' :'Terrestrial',
      'radius' : "339.6 KM",
      'des':'Earth—our home planet—is the only place we know of so far that’s inhabited by living things. It is also the only planet in our solar system with liquid water on the surface',
    },
    {
      'name': 'Mercury',
      'file': 'assets/images/Mercury.glb',
      'year' : '88 Earth Day',
      'type' :'Terrestrial',
      'radius' : "2439.4 KM",
      'des':'Mercury—the smallest planet in our solar system and closest to the Sun—is only slightly larger than Earth iss Moon. Mercury is the fastest planet, zipping around the Sun every 88 Earth days.',
    },
    {
      'name': 'Venus',
      'file': 'assets/images/Venus.glb',
      'year' : '225 Earth Days',
      'type' :'Terrestrial',
      'radius' : "6051.8 KM",
      'des':'Venus spins slowly in the opposite direction from most planets. A thick atmosphere traps heat in a runaway greenhouse effect, making it the hottest planet in our solar system.',
    },
    {
      'name': 'Mars',
      'file': 'assets/images/Mars.glb',
      'year' : '687 Earth Day',
      'type' :'Terrestrial',
      'radius' : "3396.2 KM",
      'des':'Mars is a dusty, cold, desert world with a very thin atmosphere. There is strong evidence Mars was—billions of years ago—wetter and warmer, with a thicker atmosphere.',
    },
    {
      'name': 'Jupiter',
      'file': 'assets/images/Jupiter.glb',
      'year' : '4333 Earth Day',
      'type' :'Terrestrial',
      'radius' : "71492.0 KM",
      'des': 'Jupiter is more than twice as massive than the other planets of our solar system combined. The giant planet is Great Red spot is a centuries-old storm bigger than Earth.',
    },
    {
      'name': 'Saturn',
      'file': 'assets/images/Saturn.glb',
      'year' : '10,759 Earth Day',
      'type' :'Gas Glant',
      'radius' : "60268.0 KM",
      'des': 'Adorned with a dazzling, complex system of icy rings, Saturn is unique in our solar system. The other giant planets have rings, but none are as spectacular as Saturn is.',
    },
    {
      'name': 'Neptune',
      'file': 'assets/images/Neptune.glb',
      'year' : '60,990 Earth Day',
      'type' :'Gas Glant',
      'radius' : "26764.0 KM",
      'des': 'Neptune—the eighth and most distant major planet orbiting our Sun—is dark, cold and whipped by supersonic winds. It was the first planet located through mathematical calculations, rather than by telescope.',
    },
    {
      'name': 'Sun',
      'file': 'assets/images/Sun.glb',
      'year' : '60,990 Earth Day',
      'type' :'Gas Glant',
      'radius' : "696,340.0 KM",
      'des': 'The Sun is a 4.5 billion-year-old yellow dwarf star – a hot glowing ball of hydrogen and helium – at the center of our solar system . It is about 93 million miles (150 million kilometers) from Earth and it is our solar systems only star. Without the Suns energy, life as we know it could not exist on our home planet.',
    },
    {
      'name': 'Uranus',
      'file': 'assets/images/Uranus.glb',
      'year' : '31,000 Earth Day',
      'type' :'Ice Giant',
      'radius' : "25,362.0 KM",
      'des': 'Uranus is one of two ice giants in the outer solar system (the other is Neptune). Most (80% or more) of the planets mass is made up of a hot dense fluid of "icy" materials – water, methane, and ammonia – above a small rocky core.',
    },
  ];
}